# [START app_yaml]
runtime: python27
api_version: 1
threadsafe: true



handlers:
- url: /css
  static_dir: public/css
- url: /js
  static_dir: public/js
- url: /assets
  static_dir: public/assets
- url: /models
  static_dir: public/models
- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest  
# [END app_yaml]